### ISSUE TITLE
Django Web Server is not opening

### ISSUE THREAD

**Issue by waheednaseer** [jai-singhal/croma#6]
I want to use your pharmacy web-application but when I run this command 
python3 manage.py runserver the blank command is showing instead of using this command I used this one python manage.py runserver I got [these errors](https://i.stack.imgur.com/1Qndj.png).

**Comment by jai-singhal** [comment]
In settings.py, I have mentioned locations for database and other things. You can change those location according to the need.
The error that you are getting is because it is try to create a path at E:\

**Comment by waheednaseer** [comment]
Now I got This error 
![image](https://user-images.githubusercontent.com/59465188/80142857-4d4a7c00-85c5-11ea-8283-4724083508fc.png)

**Comment by jai-singhal** [comment]
Change the database configuration in settings.py. For easier access, use dbsqlite3, it is been commented out in settings.py.
Comment current database configuration.

**Comment by waheednaseer** [comment]
How Can I fix this One! 
![image](https://user-images.githubusercontent.com/59465188/80149967-f8acfe00-85d0-11ea-8039-b18356d50d5f.png)

**Comment by jai-singhal** [comment]
You have to migrate by
python manage.py migrate

Man you need to have some basic knowledge of django and python before running the project.
