### ISSUE TITLE
Documentation and ER Diagram

### ISSUE THREAD

**Issue by hackstarsj** [jai-singhal/croma#8]
Can You Share Your Project Documentation and ER Diagram Too am Working on Same Project

**Comment by jai-singhal** [comment]
I have not created this as some freaky college project or something. This project is created for my dad that does not require any documentation or anything. 
You can generate in database tools, since the models(tables) are already created. 
And about documentation, I don't have any, refer README.

**Comment by hackstarsj** [comment]
Ok no problem Thanks
But it's very good
